apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-argo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-argo
  template:
    metadata:
      labels:
        app: web-argo
    spec:
      containers:
      - name: web-argo
        image: pse0403/spring:11
        ports:
        - containerPort: 80
